### PR TITLE
Ensure treatment erupt loop is within the objective weights scope

### PR DESCRIPTION
**Pull request by hugos0910**
### Description

Average treatment erupt curve calculation was outside of the objective weights scope, therefore only the erupt for treatments with the last set of objective weights were calculated.

### Motivation and Context

Ensure treatment erupt curves are calculated correctly.

### How Has This Been Tested?

Not tested
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added reviewers to the PR.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by samcarlos** [comment]
Hey just saw this. Let me take a look and get back to you. Thanks!

**Comment by samcarlos** [comment]
Hey @hugos0910 I don't think we want to do this. The ATE are the average treatment effects of each treatment and don't rely on objective weights. Note the objective weights are not within that loop.

Think of this step as taking the mean of each treatment. It is meant as a comparison to the ERUPT curves.

**Comment by samcarlos** [comment]
Hey going to close this for now. Let me know if you'd like to discuss.

**Comment by hugos0910** [comment]
Thanks for getting back. Isn't the y_temp used here calculated from the objective weights?

**Comment by samcarlos** [comment]
hmm it is.. I wonder if I meant to just use `y` instead of `y_temp` there as I just recorded str_obj_weight as the treatment .. but yea something is up. 

I guess my concern is that if we indent this as suggested there will be a lot of duplicated information in that data frame.

Can you please provide sample output?

**Pull request closed without merging**
